# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[ColorSchemes]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "Random"]
git-tree-sha1 = "a851fec56cb73cfdf43762999ec72eff5b86882a"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.15.0"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "024fe24d83e4a5bf5fc80501a314ce0d1aa35597"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.11.0"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "Reexport"]
git-tree-sha1 = "417b0ed7b8b838aa6ca0a87aadf1bb9eb111ce40"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.8"

[[Conda]]
deps = ["JSON", "VersionParsing"]
git-tree-sha1 = "299304989a5e6473d985212c28928899c74e9421"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.5.2"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[EchoMetrics]]
deps = ["EchogramUtils", "Statistics"]
git-tree-sha1 = "e6d4395dca80c0ec4f402538d1a9fbfbd5767cca"
repo-rev = "master"
repo-url = "git@github.com:EchoJulia/EchoMetrics.jl.git"
uuid = "24fea464-d61d-11e8-18cd-e39ec79aa639"
version = "0.1.0"

[[EchogramColorSchemes]]
deps = ["ColorSchemes", "ColorTypes", "FixedPointNumbers"]
git-tree-sha1 = "dc3eb47caac77d22209ae2536b27ebe7b03e7a97"
repo-rev = "master"
repo-url = "git@github.com:EchoJulia/EchogramColorSchemes.jl.git"
uuid = "4c5cd976-4938-5223-a900-acc20a7c8507"
version = "0.0.0"

[[EchogramPyPlot]]
deps = ["ColorSchemes", "EchogramColorSchemes", "PyPlot"]
git-tree-sha1 = "5123501ccb358d0d2b4276b679961c1bdc9321e0"
repo-rev = "master"
repo-url = "git@github.com:EchoJulia/EchogramPyPlot.jl.git"
uuid = "cefffc6e-22df-5efe-a096-e879be851ea5"
version = "0.0.0"

[[EchogramUtils]]
deps = ["Statistics"]
git-tree-sha1 = "27dd2333e52c34707b36d65581cad3cc890bb7bf"
repo-rev = "master"
repo-url = "git@github.com:EchoJulia/EchogramUtils.jl.git"
uuid = "e6c92fb4-1eaa-58f3-81b2-62c853d22af2"
version = "0.0.0"

[[FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "8076680b162ada2a031f707ac7b4953e30667a37"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.2"

[[LaTeXStrings]]
git-tree-sha1 = "c7f1c695e06c01b95a67f0cd1d34994f3e7db104"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.2.1"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "5a5bc6bf062f0f95e62d0fe0a2d99699fed82dd9"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.8"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Parsers]]
deps = ["Dates"]
git-tree-sha1 = "a8709b968a1ea6abc2dc1967cb1db6ac9a00dfb6"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.0.5"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[PyCall]]
deps = ["Conda", "Dates", "Libdl", "LinearAlgebra", "MacroTools", "Serialization", "VersionParsing"]
git-tree-sha1 = "169bb8ea6b1b143c5cf57df6d34d022a7b60c6db"
uuid = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
version = "1.92.3"

[[PyPlot]]
deps = ["Colors", "LaTeXStrings", "PyCall", "Sockets", "Test", "VersionParsing"]
git-tree-sha1 = "14c1b795b9d764e1784713941e787e1384268103"
uuid = "d330b81b-6aea-500a-939a-2ce795aea3ee"
version = "2.10.0"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SimradEK60]]
deps = ["SimradRaw"]
git-tree-sha1 = "3d5c3dfca5cb4aea6e56f108dbb3c1de3a7e705c"
repo-rev = "master"
repo-url = "git@github.com:EchoJulia/SimradEK60.jl.git"
uuid = "8e323af8-d215-5c39-b262-30cfc2fa9c48"
version = "0.0.0"

[[SimradEK60TestData]]
git-tree-sha1 = "4966999e3306c8a802d07537c1b6eca91e024176"
repo-rev = "master"
repo-url = "git@github.com:EchoJulia/SimradEK60TestData.jl.git"
uuid = "6560e86b-c63b-5eb7-baae-f1872a4305ea"
version = "0.0.0"

[[SimradRaw]]
deps = ["Test"]
git-tree-sha1 = "5c7d852f7fa30d111d90f1d90b3353947769b826"
uuid = "83a1bcd9-a884-567d-b532-90bac4ae8d51"
version = "0.1.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
git-tree-sha1 = "80229be1f670524750d905f8fc8148e5a8c4537f"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.2.0"
